### ISSUE TITLE
Error: Invalid index

### ISSUE THREAD

**Issue by A4-Cloud** [oracle-devrel/leagueoflegends-optimizer#17]
When ever I try to run ./start.sh in lab 1 I keep getting the following error 

 Error: Invalid index
│ 
│   on datascience.tf line 24, in resource "oci_datascience_notebook_session" "lol_notebook_session":
│   24:     shape = data.oci_datascience_notebook_session_shapes.ds_shapes.notebook_session_shapes[0].name
│     ├────────────────
│     │ data.oci_datascience_notebook_session_shapes.ds_shapes.notebook_session_shapes is empty list of object
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│ 
│   on datascience.tf line 44, in output "ds_notebook_session_shape":
│   44:   value = data.oci_datascience_notebook_session_shapes.ds_shapes.notebook_session_shapes[0].name
│     ├────────────────
│     │ data.oci_datascience_notebook_session_shapes.ds_shapes.notebook_session_shapes is empty list of object
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.

I don’y know what to do  I tried to look up how to fix it but nothing seems to work

**Comment by A4-Cloud** [comment]
I ment lab 2

**Comment by jasperan** [comment]
Hi @A4-Cloud, if you're still interested you can try again, we have improved / revamped the infrastructure deployment process and fixed this issue
